---
title: "Timothy Weng's resume"
author: Timothy Weng
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    self_contained: true
knit: pagedown::chrome_print
---

```{css, echo=FALSE}

:root{
  --page-width: 8.5in;
  --margin-right: 0.10in;
  --margin-left: 0.15in;
  --content-width: calc(var(--page-width) - var(--margin-right) - var(--margin-left));
  --root-font-size: 12pt;
  --sidebar-width: 12rem;
  --sidebar-background-color: #f2f2f2;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.14in;

  --sidebar-horizontal-padding: 0.15in;

  /* XXX: using px for very good precision control */
  --decorator-outer-offset-top: 10px;
  --decorator-outer-offset-left: -5.5px;
  --decorator-border-width: 1px;
  --decorator-outer-dim: 9px;
  --decorator-border: 1px solid #ccc;

  --row-blocks-padding-top: 0.5rem;
  --date-block-width: 0.7in;

  --main-blocks-title-icon-offset-left: calc(-17pt - 0.25 * var(--root-font-size));

  --viewer-background-color: #dcdcdc;
  --viewer-pages-spacing: 12px;
  --viewer-shadow-color: #313131;
}

.aside{
  width: var(--sidebar-width);
  padding: .8in var(--sidebar-horizontal-padding);
  font-size: 0.7rem;
  float: right;
  position: absolute;
  right: 0;
}

.aside h2{
  font-weight: 400;
  font-size: 1.1rem;
}

.aside .level2{
  margin-top: 0.25in;
}

#contact ul{
  margin-top: 0.05in;
  padding-left: 0;
  font-weight: 400;
  line-height: 1.75;
}

/* main */

/** big title **/
h1, h2{
  text-transform: uppercase;
}

#title{
  position: relative;
  left: 0.25in;
  margin: auto 0.25in 0.25in auto;
  line-height: 1.2;
}

#title h1{
  font-weight: 300;
  font-size: 1.8rem;
  line-height: 1.2;
}

.blocks:last-child .decorator{ /* slightly shortens it */
  margin-bottom: 0in;
}


.pagedjs_page {
    background: linear-gradient(to left,var(--sidebar-background-color),var(--sidebar-background-color) var(--sidebar-background-width),white var(--sidebar-background-width));
    --pagedjs-margin-top: .5in;
    --pagedjs-margin-right: 0.4in;
    --pagedjs-margin-left: 0.03in;
    --pagedjs-margin-bottom: .25in;
    --pagedjs-pagebox-width: 8.5in;
    --pagedjs-pagebox-height: 11in;

.date {
    flex: 0 0 var(--date-block-width);
    padding-top: calc(var(--row-blocks-padding-top) + 0.25rem)!important;
    padding-right: 0.1in;
    font-size: 0.7rem;
    text-align: right;
    line-height: 1;
    max-width: var(--date-block-width);
}

```

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> tbweng@gmail.com
- <i class="fa fa-github"></i> [github.com/tbweng](https://github.com/tbweng)
- <i class="fa fa-linkedin"></i> [linkedin.com/tbweng](https://linkedin.com/tbweng)

<i class="fa fa-cogs" aria-hidden="true"></i> Skills {#skills}
--------------------------------------------------------------------------------

- Python (Pandas, SciKit-Learn, SciPy, Matplotlib, NumPy), 
- R (Tidyverse),
- Data Analysis, 
- Advanced Statistics,
- Hypothesis-driven Testing (A/B Testing),
- Experimental Design (Randomized Control Trial), 
- Machine Learning,
- Regression Analysis (Linear, Logistic, Linear Mixed Effects),
- Containers (Docker, Singularity)
- Jupyter Notebook, AWS, Git,
- SQL, Bash, Data Visualization
- Agile
 


<i class="fa fa-graduation-cap"></i> Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### The University of Iowa

Ph.D. in Psychology (Behavioral and Cognitive Neuroscience), 2018

**Thesis:** "Brain network predictors of exercise behavior change in sedentary older adults: an emotion and decision-making perspective"

### University of Illinois at Urbana-Champaign

B.S. (Honors) in Psychology (Behavioral and Cognitive Neuroscience), 2011


<i class="far fa-newspaper"></i> Publications {#publications}
--------------------------------------------------------------------------------

For a full list of my publications (15+ articles, 500+ citations), please see my [Google Scholar](https://scholar.google.com/citations?user=FLqI1VQAAAAJ) 



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Last updated `r format(Sys.Date(), '%B %Y')`



Main
================================================================================

Timothy Weng, PhD {#title}
--------------------------------------------------------------------------------

### Computational Neuroscientist

PhD-trained computational neuroscientist with 9 years of data science experience on large-scale biomedical and behavioral research data, emphasis on human behavior \& decision-making. Unique combination of technical skills, critical thinking aptitude, and creative problem solving abilities to produce data-driven and actionable solutions. Effective communicator who regularly translates technical analyses into written reports and presentations that are understandable to both technical and non-technical audiences.

Work Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Postdoctoral Research Fellow

[Computational Neuroimaging Laboratory](http://computational-neuroimaging-lab.org/), Dell Medical School, The University of Texas at Austin

Austin, TX

2018 - present

- Build, maintain, and test Python-based ETL pipelines for processing terrabytes of multi-modal neuroimaging data on high performance computing systems
- Aggregate multiple data streams from image processing pipelines and automate production of data quality metrics and descriptive statistics 
- Deploy statistical models and machine learning algorithms in R and Python to predict brain aging from longitudinal cardiovascular health data (N = 1,000+)
- Write documentation on using [Python-based software C-PAC](https://fcp-indi.github.io/docs/latest/user/) <i class="fa fa-github"></i> for different use cases
- Identify software defects and collaborate closely with [C-PAC](https://github.com/FCP-INDI/C-PAC/) <i class="fa fa-github"></i> software engineering team to reproduce them and test patches
- Design and manage collaborative projects with multiple academic disciplines and diverse team settings
<!-- - Design research experiments and manage team of research assistants -->
<!-- - Provide feedback on the [C-PAC](https://github.com/FCP-INDI/C-PAC/) dashboard user experience -->

### Consultant

[Center for Biomedical Image Computing and Analytics](https://www.med.upenn.edu/cbica/), Perelman School of Medicine, University of Pennsylvania

Philadelphia, PA (remote)

2020 - present

- Develop infrastructure for automated and efficient data processing pipeline for functional MRI data using state-of-the-art image processing techniques
- Provide technical support and education for biomedical imaging acquisition protocols and data processing methodologies

Project Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Graduate Researcher

[Health, Brain, Cognition Laboratory](https://psychology.uiowa.edu/health-brain-cognition-lab), The University of Iowa 

Iowa City, IA

2012-2018


- Co-developed [software package](https://github.com/HBClab/RestingState) <i class="fa fa-github"></i> to optimize and automate processing of MRI data, reducing computational time by ~150\% 
- Enabled team to explore data, build statistical models, and publish results more quickly than previous implementation (10+ papers published using this codebase) 
- Utilized high performance computing cluster to parallelize pipeline execution 
- Completed 5 research projects that culminated in doctoral thesis using high-dimensional biomedical and behavioral data to predict human behavior change 
- Implemented multivariate analyses in R, including linear mixed effects modeling, principal components analysis, and MANCOVA
- Awarded first-place in departmental data competition for ability to visualize and present data clearly and succinctly 

### ANC Neighbors

Austin New Church

Austin, TX

2020

- [Data-driven geospatial analysis](https://tbweng.github.io/ANCNeighbors/map) to inform church leaders about connecting their ~460 church members across Austin metro
- Built Python-based application to load and extract from database and transform them to geospatial coordinates 
- Applied k-means clustering to identify geospatial clusters and classify new datapoints 
- Performed basic descriptive statistics and visualizations for geospatial clusters



